### ISSUE TITLE
https://www.oio.social/ does not redirect to oio.social

### ISSUE THREAD

**Issue by Adorfer** [OpenInfrastructureOrbit/oio.social#15]
for the fainted hearted....

**Comment by andibraeu** [comment]
:D

Do we really need www.? we never announced that, we never use it...

**Comment by Adorfer** [comment]
there are people who type this by default... 
it's not me, but they exist... i tried to put my website to "blog.$domain" and "$domain"... and just a redirect for www... nowhere announced, but significant hits.

**Comment by andibraeu** [comment]
done

**Comment by Adorfer** [comment]
![grafik](https://user-images.githubusercontent.com/10302493/67964842-4556e400-fc01-11e9-86cf-dde8490f7ebc.png)

**Comment by andibraeu** [comment]
hmm, maybe it is not possible with the registrar to redirect to the same domain. I tried another solution now. If that doesn't work either, we won't have www.
