### ISSUE TITLE
Spendenaufruf schreiben

### ISSUE THREAD

**Issue by andibraeu** [OpenInfrastructureOrbit/oio.social#22]
Verweis auf http://spenden.oio.social

Es kann auch per Überweisung gespendet werden:

Förderverein Freie Netzwerke e.V.
Konto 722 722 7006
BLZ 100 900 00
BIC: BEVODEBB
IBAN: DE51100900007227227006
Berliner Volksbank
Verwendungszweck: OIO auf dem 36c3

**Comment by kayschwarz** [comment]
Der Menüpunkt "Spenden" zeigt ja schon auf Betterplace. Soll da erstmal noch Prosa hin und dann verwiesen werden?

**Comment by andibraeu** [comment]
Ich dachte eher als Blogpost

**Comment by andibraeu** [comment]
so sah es letztes Jahr aus: https://oio.social/2018/11/19/call-for-participation.html
