### ISSUE TITLE
Webseite in großen Teilen des Internets nicht erreichbar!

### ISSUE THREAD

**Issue by DO1JLR** [OpenInfrastructureOrbit/oio.social#24]
Aktuell ist die oio.social Seite aus großen Teilen des Internets nicht erreichbar. Wie auch hier zu sehen:

[![asciicast](https://asciinema.org/a/4c1RXOuHkeQRksKxEcSUe9NoT.svg)](https://asciinema.org/a/4c1RXOuHkeQRksKxEcSUe9NoT)

Oder mit anderen Worten:

Es sind nun ein paar Monate seit 1998 vergangen... Meint ihr es wäre mal Zeit für IPv6?

**Comment by andibraeu** [comment]
https://github.com/isaacs/github/issues/354

:/

**Comment by andibraeu** [comment]
github pages unterstützt ipv6 nicht

**Comment by INCO-devel** [comment]
Soll ich bei uns im Verein mal nach Webspace fragen? Wir stellen sowas schon länger Uni-Clubs und anderen gemeinnützigen Vereinen zur Verfügung. Kann auch IPv6...

**Comment by Adorfer** [comment]
Platz wo man es hosten könnte haben wir zu genüge. Aber hier geht es wohl eher um die bewusste Selbstbeschränkung und die Toolchain.

**Comment by Adorfer** [comment]
Ok, dann anders formliert: Wenn jemand sagen würde "wir brauchen eine VM mit erreichbarer IPv4, IPv6 mit folgendem Stack (,an Resourcen etwas so etwas) und folgenden ssh-credentials: wäre innerhalb von weniger als 24h da.

**Comment by andibraeu** [comment]
Ein Ziel war auch, alles möglichst einfach zu halten. Z. B. wird die Website durch Commits auf den master-branch automatisch deployed. Das erleichtert die Arbeit ungemein und ermöglicht die Mitarbeit auch, wenn man keine Ahnung von den dahinterliegenden Services hat.

Wahrscheinlich werden ipv6-only Internetzugänge auch recht selten sein, zumindest in den Gebieten, die wir mit dieser Seite erreichen wollen.

**Comment by andibraeu** [comment]
Behoben: https://github.blog/changelog/2021-09-30-enabling-ipv6-support-for-github-pages/
