### ISSUE TITLE
Kerning/spacing of font path of OIO-logo very random

### ISSUE THREAD

**Issue by Adorfer** [OpenInfrastructureOrbit/oio.social#28]
this does at least not look right. (if it's intended, we should make it clear somewhere, in order to prevent people from assuming an error)
![grafik](https://user-images.githubusercontent.com/10302493/68241539-24cac780-000f-11ea-8076-0f82910ebedf.png)

**Comment by andibraeu** [comment]
wo taucht das so auf? Auf meinem Rechner sieht das Logo auf der Website so aus:

![image](https://user-images.githubusercontent.com/1162168/68247833-e7b90200-001b-11ea-92e9-5fe5a41becb7.png)

**Comment by Adorfer** [comment]
In firefox 70, egal ob windowws oder ubuntu 18.04.

![grafik](https://user-images.githubusercontent.com/10302493/68252232-3f0fa000-0025-11ea-8918-3f6982182ba7.png)

**Comment by Adorfer** [comment]
Das ist schlicht kein Pfad sondern Text.. und je nachdem ob man den richtigen Font installiert hat oder nicht rendert das halt unterschiedlich. 
Vorschlag: In Pfad umwandeln bei jemanden, der die richtige Version des Fonts installiert hat.

**Comment by andibraeu** [comment]
obsolet mit dem neuen Logo
