### ISSUE TITLE
IRC Channel auf Website hinzufügen

### ISSUE THREAD

**Issue by andibraeu** [OpenInfrastructureOrbit/oio.social#46]
#oio-stage auf hackint

wird genutzt werden, um Fragen und Kommentare fürs Bühnenprogramm über das Internet zu sammeln

**Comment by andibraeu** [comment]
Link zum Channel: https://webirc.hackint.org/#irc://irc.hackint.org/#oio-stage

(Chat Client im Browser)

**Comment by mathiashro** [comment]
Fall sollte erledigt sein, schließen?
