### ISSUE TITLE
Blog Post für Infobeamer erstellen

### ISSUE THREAD

**Issue by andibraeu** [OpenInfrastructureOrbit/oio.social#47]
Der Text ist hier: https://pad.freifunk.net/p/oio-infobeamer

@iMario @kayschwarz habt ihr Zeit, das umzusetzen?

**Comment by kayschwarz** [comment]
Hallo Andi,

PR ist gestellt.


Grüße

--

Kay

Am 20.12.19 um 17:51 schrieb Andi Bräu:
